apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
      app.kubernetes.io/name: configserver
      app.kubernetes.io/instance: configserver
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/component: microservice
      app.kubernetes.io/part-of: configserver
      app.kubernetes.io/managed-by: helm   
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: configserver
      app.kubernetes.io/version: "1.0.0"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: configserver
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - name: configserver
        image: mzegarra/configserver:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi #256Mi
        ports:
          - containerPort: 8888
        envFrom:
          - configMapRef:
              name: configserver-settings
        volumeMounts:
          - name: configserver-key
            mountPath: /config-server.jks
            subPath: config-server.jks
        env:
          - name: GIT_USER
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: username
          - name: GIT_PWD
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: password
          - name: KEYSTORE_PWD
            valueFrom:
              secretKeyRef:
                name: configserver-jks
                key: KEYSTORE_PWD
          - name: KEYSTORE_SECRET
            valueFrom:
              secretKeyRef:
                name: configserver-jks
                key: KEYSTORE_SECRET
      volumes:
        - name: configserver-key
          secret:
            secretName: configserver-key
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
      app.kubernetes.io/name: configserver
      app.kubernetes.io/instance: configserver
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/component: service
      app.kubernetes.io/part-of: configserver
      app.kubernetes.io/managed-by: helm 
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
      app.kubernetes.io/name: configserver
      app.kubernetes.io/version: "1.0.0"
  type: ClusterIP
---
